language: ruby

rvm:
- 2.0.0
- 2.1
- 2.2

env:
- CHEF_VERSION="= 0.10.10"
- CHEF_VERSION="= 10.24.0"
- CHEF_VERSION="~> 10.0"
- CHEF_VERSION="= 11.4.0"
- CHEF_VERSION="~> 12.0"

matrix:
  exclude:
  - rvm: 2.0.0
    env: CHEF_VERSION="= 10.24.0"
  - rvm: 2.0.0
    env: CHEF_VERSION="= 11.4.0"
  - rvm: 2.0.0
    env: CHEF_VERSION="~> 12.0"
  - rvm: 2.1
    env: CHEF_VERSION="~> 12.0"
  - rvm: 2.2
    env: CHEF_VERSION="= 0.10.10"
  - rvm: 2.2
    env: CHEF_VERSION="= 10.24.0"
  - rvm: 2.2
    env: CHEF_VERSION="= 11.4.0"
  - rvm: 2.2
    env: CHEF_VERSION="~> 12.0"

sudo: false
