language: ruby

rvm:
- 2.0.0
- 2.1
- 2.2

env:
- CHEF_VERSION="~> 11.0"
- CHEF_VERSION="~> 12.0"
- CHEF_VERSION="~> 13.0"

matrix:
  exclude:
  - rvm: 2.0.0
    env: CHEF_VERSION="~> 12.0"
  - rvm: 2.0.0
    env: CHEF_VERSION="~> 13.0"
  - rvm: 2.1
    env: CHEF_VERSION="~> 13.0"
  - rvm: 2.2
    env: CHEF_VERSION="~> 13.0"

sudo: false
